# Restart helper generated by Codex for 2026-07-04 shutdown prep.
# Run from PowerShell after reboot. It relaunches recorded MT5 terminals and core apps where possible.
$ErrorActionPreference = "Continue"

function Start-RecordedProcess {
  param([string]$FilePath, [string]$ArgumentList = "")
  if (-not (Test-Path -LiteralPath $FilePath)) { Write-Warning "Missing: $FilePath"; return }
  Write-Host "Starting $FilePath $ArgumentList"
  if ([string]::IsNullOrWhiteSpace($ArgumentList)) { Start-Process -FilePath $FilePath } else { Start-Process -FilePath $FilePath -ArgumentList $ArgumentList }
  Start-Sleep -Seconds 2
}

# MT5 terminals
Start-RecordedProcess -FilePath 'C:\MT5PortableGoldMission\terminal64.exe' -ArgumentList '/portable /config:C:\MT5PortableGoldMission\Config\phase1_dry_run_startup.ini'
Start-RecordedProcess -FilePath 'C:\MT5PortablePositionPathObserver\terminal64.exe' -ArgumentList '/portable /config:C:\MT5PortablePositionPathObserver\Config\position_path_observer_startup.ini'
Start-RecordedProcess -FilePath 'C:\MT5PortableRepairLane\terminal64.exe' -ArgumentList '/portable'
Start-RecordedProcess -FilePath 'C:\MT5PortableShadowFixObservers\terminal64.exe' -ArgumentList '/portable'
Start-RecordedProcess -FilePath 'C:\MT5PortableSpreadLogger\terminal64.exe' -ArgumentList '/portable /config:C:\MT5PortableSpreadLogger\Config\phase0_spread_logger_startup.ini'
Start-RecordedProcess -FilePath 'C:\MT5PortableTier1BestEA\terminal64.exe' -ArgumentList '/portable'
Start-RecordedProcess -FilePath 'C:\MT5PortableTier1PathObserver\terminal64.exe' -ArgumentList '/portable /config:C:\MT5PortableTier1PathObserver\Config\position_path_observer_startup.ini'
Start-RecordedProcess -FilePath 'C:\MT5PortableTrendGuardedFixObservers\terminal64.exe' -ArgumentList '/portable'
Start-RecordedProcess -FilePath 'C:\Program Files\MetaTrader 5\terminal64.exe' -ArgumentList ''

# Core desktop apps. Store apps may require manual launch if direct executable launch is blocked by Windows.
Start-RecordedProcess -FilePath 'C:\Program Files\Google\Chrome\Application\chrome.exe' -ArgumentList '--restore-last-session'
Start-RecordedProcess -FilePath 'C:\Program Files\WindowsApps\OpenAI.Codex_26.623.13972.0_x64__2p2nqsd0c76g0\app\Codex.exe'
Start-RecordedProcess -FilePath 'C:\Program Files\WindowsApps\OpenAI.ChatGPT-Desktop_1.2026.133.0_x64__2p2nqsd0c76g0\app\ChatGPT.exe'
Start-RecordedProcess -FilePath 'C:\Program Files\WindowsApps\Claude_1.18286.0.0_x64__pzs8sxrjxfjjc\app\claude.exe'

Write-Host "Restart helper complete. Verify MT5 account/window titles manually after launch."
