from __future__ import annotations

import importlib


def test_required_modules_import():
    module_names = [
        "phase0",
        "phase0.artifact_verifier",
        "phase0.adversarial",
        "phase0.aggregation",
        "phase0.backtester",
        "phase0.bar_builder",
        "phase0.candles",
        "phase0.cli",
        "phase0.config",
        "phase0.constants",
        "phase0.costs",
        "phase0.data_contracts",
        "phase0.data_availability",
        "phase0.data_import",
        "phase0.data_loader",
        "phase0.data_validator",
        "phase0.deciles",
        "phase0.execution",
        "phase0.gates",
        "phase0.gold_fx_proxy_data",
        "phase0.hashing",
        "phase0.holdout",
        "phase0.indicators",
        "phase0.intrabar",
        "phase0.levels",
        "phase0.manifests",
        "phase0.metrics",
        "phase0.matrix",
        "phase0.multisymbol",
        "phase0.mt5_presets",
        "phase0.normalizer",
        "phase0.reports",
        "phase0.reference",
        "phase0.run_context",
        "phase0.safety",
        "phase0.sizing",
        "phase0.snapshot",
        "phase0.spread_analysis",
        "phase0.trades",
        "phase0.utils",
        "phase0.workflow",
        "phase0.xau_xag_relative_data",
        "phase0.strategies.base",
        "phase0.strategies.trend_pullback",
        "phase0.strategies.breakout_retest",
        "phase0.strategies.gold_fx_proxy_divergence_v0",
        "phase0.strategies.h1_calendar_drift_state_v0",
        "phase0.strategies.h1_m5_path_skew_reversal_v0",
        "phase0.strategies.h1_return_autocorrelation_state_v0",
        "phase0.strategies.h1_tick_volume_climax_reversal_v0",
        "phase0.strategies.h1_walk_forward_linear_state_v0",
        "phase0.strategies.range_mr",
        "phase0.strategies.registry",
        "phase0.strategies.xau_xag_relative_value_v0",
        "phase0.synthetic",
    ]

    for module_name in module_names:
        importlib.import_module(module_name)
