"""Enter ON microstructure, instead of filtering a price pattern with it.

The measured fact this is built on: gold's profit factor falls from 1.89 to 1.10
on the test era when three features are removed - tick_signed_move,
tick_book_imbalance_mean, price_efficiency_5m. Most of the edge lives there. Yet
every system in this corpus uses them only to RANK candidates generated by a
price rule (a dip, or a confirmation excursion).

So the question nobody has asked: if the microstructure is where the information
is, what happens when it generates the entries itself?

Four candidate triggers, each a different reading of what order flow is saying.
All share the same execution mechanics as the incumbent so the comparison is
clean: stop 6.75xATR144, exit at stop or horizon close, 07-17 UTC, 30-min grid.
No confirmation excursion, no dip gate, no macro filter - those are the price
rules being replaced.

  ABSORPTION   heavy signed tick flow that produced little price movement -
               someone is absorbing it, and price tends to go the other way
  IMBALANCE    sustained book imbalance - directional pressure in the quotes
  EFFICIENCY   a low-efficiency (choppy) stretch resolving, taken in the
               direction of the accumulated flow
  FLOW_BREAK   tick flow and price agreeing strongly - continuation

PREREGISTERED BEFORE RUNNING:
  * fit/threshold on trades entered on or before 2024-12-31; 2025-01 sealed
  * a trigger is interesting only if it clears PF >= 1.20 on BOTH eras with
    n >= 150 in each - the same gate the multi-instrument lane used
  * benchmark: V6 walk-forward PF 1.42 is the bar this corpus has to beat
  * report every trigger and both directions; no picking the best afterwards
"""
import argparse, itertools
import numpy as np, pandas as pd
import engine, specialist

FIT_END = pd.Timestamp("2024-12-31 23:59:59", tz="UTC")
STOP_MULT, HZ, GRID, LO, HI = 6.75, 432, 30, 7, 17
LOOK = 24                    # 2h lookback for the microstructure state


def signals(C, kind, z_thresh):
    """Return (index, long) pairs where the trigger fires."""
    n = C["n"]
    mc, atr, slope = C["mc"], C["atr"], C["slope"]
    csm, cbi, ctc, cts, cpe = C["csm"], C["cbi"], C["ctc"], C["cts"], C["cpe"]
    ok = ((C["minute"] % GRID == 0) & (C["hour"] >= LO) & (C["hour"] < HI)
          & np.isfinite(atr) & (atr > 0))
    idx = np.flatnonzero(ok)
    idx = idx[(idx >= LOOK + 2016) & (idx + 2 < n)]

    # microstructure state over the trailing LOOK bars, all backward-looking
    flow = (csm[idx] - csm[idx - LOOK]) / LOOK          # net signed tick move
    imb = (cbi[idx] - cbi[idx - LOOK]) / LOOK           # mean book imbalance
    eff = (cpe[idx] - cpe[idx - LOOK]) / LOOK           # mean price efficiency
    act = (ctc[idx] - ctc[idx - LOOK]) / LOOK           # tick activity
    move = (mc[idx] - mc[idx - LOOK]) / atr[idx]        # actual price move, ATR units

    def z(x):
        s = pd.Series(x)
        return ((s - s.rolling(2000, min_periods=200).mean())
                / (s.rolling(2000, min_periods=200).std() + 1e-9)).values

    zf, zi, ze, za, zm = z(flow), z(imb), z(eff), z(act), z(move)

    if kind == "ABSORPTION":
        # strong flow, weak resulting move -> fade the flow
        fire = (np.abs(zf) > z_thresh) & (np.abs(zm) < 0.5)
        long = zf < 0
    elif kind == "IMBALANCE":
        fire = np.abs(zi) > z_thresh
        long = zi > 0
    elif kind == "EFFICIENCY":
        # choppy stretch (low efficiency) + directional flow -> take the flow
        fire = (ze < -z_thresh) & (np.abs(zf) > 0.5)
        long = zf > 0
    else:                       # FLOW_BREAK: flow and price agree strongly
        fire = (np.abs(zf) > z_thresh) & (np.sign(zf) == np.sign(zm)) & (np.abs(zm) > 0.5)
        long = zf > 0
    fire &= np.isfinite(zf) & np.isfinite(zi) & np.isfinite(ze) & np.isfinite(zm)
    return idx[fire], long[fire]


def run(C, kind, z_thresh):
    ix, lg = signals(C, kind, z_thresh)
    if len(ix) < 60:
        return None
    n, t = C["n"], C["t"]
    atr = C["atr"]
    bl, bc, ao, ah, ac, bo = C["bl"], C["bc"], C["ao"], C["ah"], C["ac"], C["bo"]
    rows, pend = [], []
    for k in range(len(ix)):
        i, long = int(ix[k]), bool(lg[k])
        stop = STOP_MULT * atr[i]
        if not stop > 0:
            continue
        j, i1 = i + 1, min(i + 1 + HZ, n)
        if i1 - j < 20:
            continue
        # one position at a time, released at the actual exit (entry-order book)
        pend = [p for p in pend if p > t.iloc[j]]
        if pend:
            continue
        if long:
            fill = ao[j]; slv = fill - stop
            hit = np.flatnonzero(bl[j:i1] <= slv)
            xi = j + hit[0] if len(hit) else i1 - 1
            xp = slv if len(hit) else bc[xi]
            r = (xp - fill) / stop - engine.FEE / stop
        else:
            fill = bo[j]; slv = fill + stop
            hit = np.flatnonzero(ah[j:i1] >= slv)
            xi = j + hit[0] if len(hit) else i1 - 1
            xp = slv if len(hit) else ac[xi]
            r = (fill - xp) / stop - engine.FEE / stop
        rows.append((t.iloc[i], t.iloc[j], t.iloc[xi], long, r, stop))
        pend.append(t.iloc[xi])
    if len(rows) < 60:
        return None
    d = pd.DataFrame(rows, columns=["dec_t", "entry_t", "exit_t", "long", "r", "stop"])
    d["usd"] = d.r * d.stop
    return d


def era(d, lo, hi=None):
    g = d[d.entry_t <= FIT_END] if hi == "fit" else d[d.entry_t > FIT_END]
    if len(g) < 20:
        return None
    w, l = g[g.usd > 0], g[g.usd <= 0]
    eq = g.sort_values("exit_t").usd.cumsum()
    return dict(n=len(g), wr=round(100 * len(w) / len(g), 1),
                pf=round(float(w.usd.sum() / max(-l.usd.sum(), 1e-9)), 3),
                usd=round(float(g.usd.sum())),
                dd=round(float((eq.cummax() - eq).max())))


def main():
    ap = argparse.ArgumentParser()
    a = ap.parse_args()
    C = specialist.load_context()
    print("Entering ON microstructure. Same stop/horizon/session as the incumbent.")
    print("Gate: PF >= 1.20 on BOTH eras, n >= 150 each. Bar to beat: V6 walk-forward 1.42\n")
    print(f"{'trigger':<14}{'z':>5}{'FIT n':>7}{'WR':>7}{'PF':>8}{'USD':>9}"
          f"   {'SEALED n':>9}{'WR':>7}{'PF':>8}{'USD':>9}{'maxDD':>8}  gate")
    hits = []
    for kind in ("ABSORPTION", "IMBALANCE", "EFFICIENCY", "FLOW_BREAK"):
        for zt in (1.0, 1.5, 2.0):
            d = run(C, kind, zt)
            if d is None:
                continue
            f_ = era(d, None, "fit"); s_ = era(d, None, None)
            if not f_ or not s_:
                continue
            ok = (f_["pf"] >= 1.20 and s_["pf"] >= 1.20
                  and f_["n"] >= 150 and s_["n"] >= 150)
            if ok:
                hits.append((kind, zt, f_, s_))
            print(f"{kind:<14}{zt:>5}{f_['n']:>7}{f_['wr']:>6}%{f_['pf']:>8}{f_['usd']:>9}"
                  f"   {s_['n']:>9}{s_['wr']:>6}%{s_['pf']:>8}{s_['usd']:>9}{s_['dd']:>8}"
                  f"  {'PASS' if ok else ''}")
    print(f"\n{len(hits)} of 12 cells cleared the gate")
    if not hits:
        print("  -> entering on microstructure does not work with these triggers")


if __name__ == "__main__":
    main()
