from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


LOWFREQ_GATE_TEST_PATHS = [
    "tests/test_second_ea_research_gates.py",
    "tests/test_second_ea_research_safety.py",
]


SECOND_EA_FOCUSED_TEST_PATHS = [
    "tests/test_second_ea_missing_inputs.py",
    "tests/test_second_ea_goal_audit.py",
    "tests/test_second_ea_data_readiness.py",
    "tests/test_second_ea_blocked_artifacts.py",
    "tests/test_second_ea_hypotheses.py",
    "tests/test_second_ea_research_gates.py",
    "tests/test_second_ea_preflight.py",
    "tests/test_lane_a_reconstruction.py",
    "tests/test_event_clocks.py",
    "tests/test_cli.py",
    "tests/test_second_ea_partial_data_decision.py",
    "tests/test_second_ea_research_safety.py",
    "tests/test_second_ea_lowfreq_gate_report.py",
    "tests/test_second_ea_campaign_status.py",
]


@dataclass(frozen=True)
class VerificationResult:
    name: str
    command: str
    status: str
    summary: str


def run_pytest_verification(project_root: Path, name: str, test_paths: list[str]) -> VerificationResult:
    command = [sys.executable, "-m", "pytest", *test_paths]
    completed = subprocess.run(
        command,
        cwd=project_root,
        text=True,
        capture_output=True,
        check=False,
    )
    output = "\n".join(part for part in (completed.stdout, completed.stderr) if part)
    return VerificationResult(
        name=name,
        command=_display_command(test_paths),
        status="PASS" if completed.returncode == 0 else "FAIL",
        summary=_pytest_summary(output, completed.returncode),
    )


def write_low_frequency_gate_test_report(
    project_root: Path,
    verifications: list[VerificationResult],
    generated_at: str | None = None,
) -> Path:
    generated = generated_at or datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    report_path = project_root / "outputs" / "reports" / "SECOND_EA_LOW_FREQ_GATE_TESTS.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    overall_status = "PASS" if all(result.status == "PASS" for result in verifications) else "FAIL"

    lines = [
        "# Second EA Low-Frequency Gate Tests",
        "",
        f"Status: {overall_status}",
        f"Generated at UTC: {generated}",
        "",
        "The low-frequency gate formulas are implemented in `src/phase0/low_frequency_gates.py`.",
        "",
        "This report is generated by `scripts/generate_second_ea_lowfreq_gate_tests.py`.",
        "",
        "## Verification Commands",
        "",
    ]
    for result in verifications:
        lines.extend(
            [
                f"### {result.name}",
                "",
                "```powershell",
                result.command,
                "```",
                "",
                f"Status: {result.status}",
                f"Result: {result.summary}",
                "",
            ]
        )
    lines.extend(
        [
            "## Boundary",
            "",
            "These commands are static repo-local tests only. They do not authorize MT5 runtime access, observer deployment, demo execution, live execution, paper trading, or broker action.",
            "",
        ]
    )
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def _display_command(test_paths: list[str]) -> str:
    return " ".join(["python", "-m", "pytest", *test_paths])


def _pytest_summary(output: str, returncode: int) -> str:
    for line in reversed(output.splitlines()):
        stripped = line.strip()
        if stripped.startswith("=") and (" passed" in stripped or " failed" in stripped):
            return stripped.strip("= ").strip()
    return f"pytest exited with code {returncode}"
